### PR TITLE
Add sequence diagrams for worker-controller interactions and lstm mainloop

### PR DESCRIPTION
**Pull request by carriepl**
I am not certain what the best place to put those is but, at the moment, I created a 'doc' folder at the root of the platoon directory with a (sub-folder structure resembling that of the platoon directory itself) and placed the diagrams in the sub-folders analogous to the directories of the documented classes/scripts.

### CODE REVIEW

**Comment by dwf** [comment]
Are there source files of some sort for these? It would be useful to have
those under version control.

**Comment by carriepl** [comment]
No, I tried a few systems I knew about where you could define a sequence diagram via some standardized source but most of these had issues, either cluttering the elements to the point where a lot of stuff became hard to read/parse or lack of support for part of the notation(for instance, so many of those systems don't support the ':' at the beginning of a component's name). Do you know of any good system for this? At some point, I just lost patience and decided a sub-optimal diagram was still better than none.

**Comment by dwf** [comment]
I was just thinking like, Inkscape or Illustrator source files or
something, not necessarily human readable source. It'd be good to have
vectors in case there ever a reason to rescale them or print them.

**Comment by carriepl** [comment]
Oh, I see what you mean. No but the files have decent resolution (300 DPI which should be suitable for printing) and they all fit within a standard 8.5 by 11 inches sheet of paper.

**Comment by bartvm** [comment]
Why not just upload SVG files instead of PNG? Both can be displayed in browsers, and SVG files can be edited by people.

**Comment by carriepl** [comment]
@bartvm : Done

**Pull request merged**
