### PR TITLE
Renamed Lieutenant and Soldier to Controller and Worker

### PR DESCRIPTION
**Pull request by mgermain**

### CODE REVIEW

**Comment by mgermain** [comment]
Fix #16

**Comment by carriepl** [comment]
I agree with the code modifications but you also need to update the documentation to be in sync. I saw references to the old name scheme in the file README.md at the repository level and the file readme.txt in the LSTM example.

**Comment by carriepl** [comment]
Also, I assume the LSTM example was tested after the modifications, just to be sure?

**Comment by mgermain** [comment]
@carriepl Yup the example was tested and thanks for spotting that I'll change the README

**Comment by carriepl** [comment]
It looks good to me as it is. I'm merging.

**Pull request merged**
