### PR TITLE
Bump up Platoon version to 0.6.0

### PR DESCRIPTION
**Pull request by tsirif**

### CODE REVIEW

**Comment by nouiz** [comment]
Good idea.

I think you could send an email to theano-dev and theano-user to tell it and make a PR to theano/doc/index.txt to add this information in the news.

**Comment by tsirif** [comment]
Also, I think that issues should be updated. I will make an effort to see which issues are still meaningfully ongoing. Should we also generate doc files for Platoon? I would like to write user instructions somewhere in details. Finally, what is your opinion on my suggestions that I sent you?

**Comment by nouiz** [comment]
Good idea to go over the current issues.

Which platoon doc do you talk about that you want to generate? I think the only doc is on github. Did I forget something? Or are you suggesting a different way to have platoon docs?

I saw your email. I just didn't got time to reply. There was much stuff to write about it!

**Comment by tsirif** [comment]
I am suggesting if we should host a documentation site. :)

**Comment by nouiz** [comment]
I like the idea. Do you propose to do it?

I think it would be better to just use something in the cloud, like
readthedocs or github pages. It would make maintenance easier. Suggestion?

Can you open an issue about this? Just to give it the right visibility.

**Pull request merged**
